CREATE DATABASE EMPRESABDS
CREATE TABLE PERSONA (
IDPERSONA INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDPERSONA),
);
CREATE TABLE EMPLEADOS (
IDEMPLEADO INT IDENTITY (1,1) NOT NULL,
IDPERSONA INT NOT NULL,
PUESTO NVARCHAR (50) NOT NULL,
FECHA_CONTRATACION DATETIME NOT NULL,
SALARIO VARCHAR (10) NOT NULL,
PRIMARY KEY (IDEMPLEADO),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA)
);

INSERT INTO PERSONA VALUES ('Jhoel','Serrudo','Activo');
INSERT INTO PERSONA VALUES ('Sergio', 'Velasquez','Inactivo');
INSERT INTO PERSONA VALUES ('Franklin', 'Socompi','Activo');
INSERT INTO PERSONA VALUES ('Fernando','Rodriguez','Inactivo');
SELECT * FROM PERSONA
INSERT INTO EMPLEADOS VALUES (1,'Jefe','2022-01-09 12:47:29','700');
INSERT INTO EMPLEADOS VALUES (2,'Gerente','2022-08-01 16:14:40','600');
INSERT INTO EMPLEADOS VALUES (3,'Tecnico','2022-04-07 13:36:01','400');
INSERT INTO EMPLEADOS VALUES (4	,'Empleado','2022-02-05 09:25:25','200');
SELECT * FROM EMPLEADOS